version: "3"

services:
  aba-keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    restart: always
    container_name: aba-keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm.json
#      - KC_PROXY=edge
#      - KC_HOSTNAME=login.abablockchain.io
#      - PROXY_ADDRESS_FORWARDING=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://${POSTGRES_URL}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_DB_SCHEMA=public
      - KC_DB_SCHEMA_AUTO=update
    ports:
      - 9000:9000
      - 8081:8080
      - 8443:8443
    volumes:
      - ./data:/opt/keycloak/data/
      - ./themes:/opt/keycloak/themes/
      - ./providers:/opt/keycloak/providers
      - ./certs:/etc/x509/https:ro
   #command: start --https-certificate-file=/etc/x509/https/tls.crt --https-certificate-key-file=/etc/x509/https/tls.key --hostname-strict=false
    command: start-dev
        
networks:
  postgres_default:
    external: true
